version: "3.9"

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: userdb
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/migrations/001_create_users.sql:/docker-entrypoint-initdb.d/001_create_users.sql

  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: userdb
      SERVER_PORT: 3000
    depends_on:
      - db

  redis:
    image: redis:7-alpine
    ports:
    - "6379:6379"


volumes:
  pgdata:


  
  
