// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: internal/email/proto/email.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendActivationEmailRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Email          string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	ActivationCode string                 `protobuf:"bytes,3,opt,name=activation_code,json=activationCode,proto3" json:"activation_code,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SendActivationEmailRequest) Reset() {
	*x = SendActivationEmailRequest{}
	mi := &file_internal_email_proto_email_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendActivationEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendActivationEmailRequest) ProtoMessage() {}

func (x *SendActivationEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_email_proto_email_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendActivationEmailRequest.ProtoReflect.Descriptor instead.
func (*SendActivationEmailRequest) Descriptor() ([]byte, []int) {
	return file_internal_email_proto_email_proto_rawDescGZIP(), []int{0}
}

func (x *SendActivationEmailRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SendActivationEmailRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SendActivationEmailRequest) GetActivationCode() string {
	if x != nil {
		return x.ActivationCode
	}
	return ""
}

type SendActivationEmailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Messsage      string                 `protobuf:"bytes,2,opt,name=messsage,proto3" json:"messsage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendActivationEmailResponse) Reset() {
	*x = SendActivationEmailResponse{}
	mi := &file_internal_email_proto_email_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendActivationEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendActivationEmailResponse) ProtoMessage() {}

func (x *SendActivationEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_email_proto_email_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendActivationEmailResponse.ProtoReflect.Descriptor instead.
func (*SendActivationEmailResponse) Descriptor() ([]byte, []int) {
	return file_internal_email_proto_email_proto_rawDescGZIP(), []int{1}
}

func (x *SendActivationEmailResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SendActivationEmailResponse) GetMesssage() string {
	if x != nil {
		return x.Messsage
	}
	return ""
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_internal_email_proto_email_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_email_proto_email_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_internal_email_proto_email_proto_rawDescGZIP(), []int{2}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ready         bool                   `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_internal_email_proto_email_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_email_proto_email_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_internal_email_proto_email_proto_rawDescGZIP(), []int{3}
}

func (x *HealthResponse) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *HealthResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_internal_email_proto_email_proto protoreflect.FileDescriptor

const file_internal_email_proto_email_proto_rawDesc = "" +
	"\n" +
	" internal/email/proto/email.proto\x12\x05email\"t\n" +
	"\x1aSendActivationEmailRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12'\n" +
	"\x0factivation_code\x18\x03 \x01(\tR\x0eactivationCode\"S\n" +
	"\x1bSendActivationEmailResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1a\n" +
	"\bmesssage\x18\x02 \x01(\tR\bmesssage\"\x0f\n" +
	"\rHealthRequest\"@\n" +
	"\x0eHealthResponse\x12\x14\n" +
	"\x05ready\x18\x01 \x01(\bR\x05ready\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xa8\x01\n" +
	"\fEmailService\x12\\\n" +
	"\x13SendActivationEmail\x12!.email.SendActivationEmailRequest\x1a\".email.SendActivationEmailResponse\x12:\n" +
	"\vCheckHealth\x12\x14.email.HealthRequest\x1a\x15.email.HealthResponseB%Z#user-api/internal/email/proto;protob\x06proto3"

var (
	file_internal_email_proto_email_proto_rawDescOnce sync.Once
	file_internal_email_proto_email_proto_rawDescData []byte
)

func file_internal_email_proto_email_proto_rawDescGZIP() []byte {
	file_internal_email_proto_email_proto_rawDescOnce.Do(func() {
		file_internal_email_proto_email_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_email_proto_email_proto_rawDesc), len(file_internal_email_proto_email_proto_rawDesc)))
	})
	return file_internal_email_proto_email_proto_rawDescData
}

var file_internal_email_proto_email_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internal_email_proto_email_proto_goTypes = []any{
	(*SendActivationEmailRequest)(nil),  // 0: email.SendActivationEmailRequest
	(*SendActivationEmailResponse)(nil), // 1: email.SendActivationEmailResponse
	(*HealthRequest)(nil),               // 2: email.HealthRequest
	(*HealthResponse)(nil),              // 3: email.HealthResponse
}
var file_internal_email_proto_email_proto_depIdxs = []int32{
	0, // 0: email.EmailService.SendActivationEmail:input_type -> email.SendActivationEmailRequest
	2, // 1: email.EmailService.CheckHealth:input_type -> email.HealthRequest
	1, // 2: email.EmailService.SendActivationEmail:output_type -> email.SendActivationEmailResponse
	3, // 3: email.EmailService.CheckHealth:output_type -> email.HealthResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_email_proto_email_proto_init() }
func file_internal_email_proto_email_proto_init() {
	if File_internal_email_proto_email_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_email_proto_email_proto_rawDesc), len(file_internal_email_proto_email_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_email_proto_email_proto_goTypes,
		DependencyIndexes: file_internal_email_proto_email_proto_depIdxs,
		MessageInfos:      file_internal_email_proto_email_proto_msgTypes,
	}.Build()
	File_internal_email_proto_email_proto = out.File
	file_internal_email_proto_email_proto_goTypes = nil
	file_internal_email_proto_email_proto_depIdxs = nil
}
