// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql"
	"time"
)

type Address struct {
	ID         int32          `json:"id"`
	UserID     int32          `json:"user_id"`
	Line1      string         `json:"line1"`
	Line2      sql.NullString `json:"line2"`
	City       string         `json:"city"`
	State      string         `json:"state"`
	PostalCode string         `json:"postal_code"`
	Country    string         `json:"country"`
	CreatedAt  sql.NullTime   `json:"created_at"`
	UpdatedAt  sql.NullTime   `json:"updated_at"`
}

type User struct {
	ID                int32          `json:"id"`
	Name              string         `json:"name"`
	Dob               time.Time      `json:"dob"`
	Email             string         `json:"email"`
	PasswordHash      string         `json:"password_hash"`
	Role              string         `json:"role"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         time.Time      `json:"updated_at"`
	IsActive          bool           `json:"is_active"`
	ActivationToken   sql.NullString `json:"activation_token"`
	ActivationExpires sql.NullTime   `json:"activation_expires"`
	LastEmailSentAt   sql.NullTime   `json:"last_email_sent_at"`
	EmailSendCount    int32          `json:"email_send_count"`
}
