// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const activateUser = `-- name: ActivateUser :exec
UPDATE users
SET is_active          = true,
    activation_token   = NULL,
    activation_expires = NULL
WHERE id = $1
`

func (q *Queries) ActivateUser(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, activateUser, id)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (name, email, password_hash, role, dob)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, email, role, dob, created_at
`

type CreateUserParams struct {
	Name         string    `json:"name"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	Role         string    `json:"role"`
	Dob          time.Time `json:"dob"`
}

type CreateUserRow struct {
	ID        int32     `json:"id"`
	Name      string    `json:"name"`
	Email     string    `json:"email"`
	Role      string    `json:"role"`
	Dob       time.Time `json:"dob"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Name,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
		arg.Dob,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Role,
		&i.Dob,
		&i.CreatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getAddressByUserID = `-- name: GetAddressByUserID :one
SELECT id, user_id, line1, line2, city, state, postal_code, country
FROM addresses WHERE user_id = $1
`

type GetAddressByUserIDRow struct {
	ID         int32          `json:"id"`
	UserID     int32          `json:"user_id"`
	Line1      string         `json:"line1"`
	Line2      sql.NullString `json:"line2"`
	City       string         `json:"city"`
	State      string         `json:"state"`
	PostalCode string         `json:"postal_code"`
	Country    string         `json:"country"`
}

func (q *Queries) GetAddressByUserID(ctx context.Context, userID int32) (GetAddressByUserIDRow, error) {
	row := q.db.QueryRowContext(ctx, getAddressByUserID, userID)
	var i GetAddressByUserIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Line1,
		&i.Line2,
		&i.City,
		&i.State,
		&i.PostalCode,
		&i.Country,
	)
	return i, err
}

const getUserActivationMeta = `-- name: GetUserActivationMeta :one
SELECT id, email, is_active, email_send_count, last_email_sent_at
FROM users WHERE email = $1
`

type GetUserActivationMetaRow struct {
	ID              int32        `json:"id"`
	Email           string       `json:"email"`
	IsActive        bool         `json:"is_active"`
	EmailSendCount  int32        `json:"email_send_count"`
	LastEmailSentAt sql.NullTime `json:"last_email_sent_at"`
}

func (q *Queries) GetUserActivationMeta(ctx context.Context, email string) (GetUserActivationMetaRow, error) {
	row := q.db.QueryRowContext(ctx, getUserActivationMeta, email)
	var i GetUserActivationMetaRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.IsActive,
		&i.EmailSendCount,
		&i.LastEmailSentAt,
	)
	return i, err
}

const getUserByActivationToken = `-- name: GetUserByActivationToken :one
SELECT id, email, is_active, activation_token, activation_expires
FROM users WHERE activation_token = $1
`

type GetUserByActivationTokenRow struct {
	ID                int32          `json:"id"`
	Email             string         `json:"email"`
	IsActive          bool           `json:"is_active"`
	ActivationToken   sql.NullString `json:"activation_token"`
	ActivationExpires sql.NullTime   `json:"activation_expires"`
}

func (q *Queries) GetUserByActivationToken(ctx context.Context, activationToken sql.NullString) (GetUserByActivationTokenRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByActivationToken, activationToken)
	var i GetUserByActivationTokenRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.IsActive,
		&i.ActivationToken,
		&i.ActivationExpires,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, email, password_hash, role, dob,is_active
FROM users WHERE email = $1
`

type GetUserByEmailRow struct {
	ID           int32     `json:"id"`
	Name         string    `json:"name"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	Role         string    `json:"role"`
	Dob          time.Time `json:"dob"`
	IsActive     bool      `json:"is_active"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Dob,
		&i.IsActive,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT id, name, email, role, dob,is_active
FROM users WHERE id = $1
`

type GetUserByIdRow struct {
	ID       int32     `json:"id"`
	Name     string    `json:"name"`
	Email    string    `json:"email"`
	Role     string    `json:"role"`
	Dob      time.Time `json:"dob"`
	IsActive bool      `json:"is_active"`
}

func (q *Queries) GetUserById(ctx context.Context, id int32) (GetUserByIdRow, error) {
	row := q.db.QueryRowContext(ctx, getUserById, id)
	var i GetUserByIdRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Role,
		&i.Dob,
		&i.IsActive,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, name, dob FROM users ORDER BY id LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListUsersRow struct {
	ID   int32     `json:"id"`
	Name string    `json:"name"`
	Dob  time.Time `json:"dob"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Dob); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setActivationToken = `-- name: SetActivationToken :exec
UPDATE users
SET activation_token        = $1,
    activation_expires      = $2,
    activation_requested_at = NOW(),
    last_email_sent_at          = NOW(),
    email_send_count            = resend_count + 1
WHERE id = $3
`

type SetActivationTokenParams struct {
	ActivationToken   sql.NullString `json:"activation_token"`
	ActivationExpires sql.NullTime   `json:"activation_expires"`
	ID                int32          `json:"id"`
}

func (q *Queries) SetActivationToken(ctx context.Context, arg SetActivationTokenParams) error {
	_, err := q.db.ExecContext(ctx, setActivationToken, arg.ActivationToken, arg.ActivationExpires, arg.ID)
	return err
}

const updatePassword = `-- name: UpdatePassword :one
UPDATE users SET password_hash = $1
WHERE id = $2
RETURNING id, name, email, dob
`

type UpdatePasswordParams struct {
	PasswordHash string `json:"password_hash"`
	ID           int32  `json:"id"`
}

type UpdatePasswordRow struct {
	ID    int32     `json:"id"`
	Name  string    `json:"name"`
	Email string    `json:"email"`
	Dob   time.Time `json:"dob"`
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) (UpdatePasswordRow, error) {
	row := q.db.QueryRowContext(ctx, updatePassword, arg.PasswordHash, arg.ID)
	var i UpdatePasswordRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Dob,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users SET name = $1, email = $2, dob = $3
WHERE id = $4
RETURNING id, name, email, dob
`

type UpdateUserParams struct {
	Name  string    `json:"name"`
	Email string    `json:"email"`
	Dob   time.Time `json:"dob"`
	ID    int32     `json:"id"`
}

type UpdateUserRow struct {
	ID    int32     `json:"id"`
	Name  string    `json:"name"`
	Email string    `json:"email"`
	Dob   time.Time `json:"dob"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.Name,
		arg.Email,
		arg.Dob,
		arg.ID,
	)
	var i UpdateUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Dob,
	)
	return i, err
}

const upsertAddress = `-- name: UpsertAddress :one
INSERT INTO addresses (user_id, line1, line2, city, state, postal_code, country)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (user_id)
DO UPDATE SET
    line1       = EXCLUDED.line1,
    line2       = EXCLUDED.line2,
    city        = EXCLUDED.city,
    state       = EXCLUDED.state,
    postal_code = EXCLUDED.postal_code,
    country     = EXCLUDED.country,
    updated_at  = NOW()
RETURNING id, user_id, line1, line2, city, state, postal_code, country
`

type UpsertAddressParams struct {
	UserID     int32          `json:"user_id"`
	Line1      string         `json:"line1"`
	Line2      sql.NullString `json:"line2"`
	City       string         `json:"city"`
	State      string         `json:"state"`
	PostalCode string         `json:"postal_code"`
	Country    string         `json:"country"`
}

type UpsertAddressRow struct {
	ID         int32          `json:"id"`
	UserID     int32          `json:"user_id"`
	Line1      string         `json:"line1"`
	Line2      sql.NullString `json:"line2"`
	City       string         `json:"city"`
	State      string         `json:"state"`
	PostalCode string         `json:"postal_code"`
	Country    string         `json:"country"`
}

func (q *Queries) UpsertAddress(ctx context.Context, arg UpsertAddressParams) (UpsertAddressRow, error) {
	row := q.db.QueryRowContext(ctx, upsertAddress,
		arg.UserID,
		arg.Line1,
		arg.Line2,
		arg.City,
		arg.State,
		arg.PostalCode,
		arg.Country,
	)
	var i UpsertAddressRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Line1,
		&i.Line2,
		&i.City,
		&i.State,
		&i.PostalCode,
		&i.Country,
	)
	return i, err
}
